# Generated by Django 5.1.7 on 2025-03-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_updated_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Sender IDs',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.senderid'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
