# Generated by Django 5.1.7 on 2025-03-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_campaigndetails_reportdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetails',
            name='receiver',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
