# Generated by Django 5.1.7 on 2025-03-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_reportdetails_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdetails',
            name='receiver',
            field=models.JSONField(),
        ),
    ]
