# Generated by Django 5.1.7 on 2025-03-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_alter_reportdetails_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndetails',
            name='campaign_name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
