# Generated by Django 5.1.7 on 2025-03-25 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0006_campaigndetails_campaign_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_updated_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SendSmsApiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('content_type', models.IntegerField()),
                ('errorCode', models.IntegerField()),
                ('actual_msgCount', models.IntegerField()),
                ('actual_messageId', models.CharField(max_length=255)),
                ('actual_current_balance', models.IntegerField()),
                ('user_msgCount', models.IntegerField()),
                ('user_messageId', models.CharField(max_length=255)),
                ('user_current_balance', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
