# Generated by Django 5.1.7 on 2025-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0007_apicredentials_sendsmsapiresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsmsapiresponse',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendsmsapiresponse',
            name='msg_type',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendsmsapiresponse',
            name='receiver',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
