# Generated by Django 5.1.7 on 2025-04-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0008_sendsmsapiresponse_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message_id', models.CharField(db_index=True, max_length=255)),
                ('actual_message_id', models.CharField(db_index=True, max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], max_length=20)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('next_check_at', models.DateTimeField()),
                ('check_attempts', models.IntegerField(default=0)),
                ('webhook_sent', models.BooleanField(default=False)),
                ('webhook_sent_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
